# DEV CONFIG
server:
  port: 8090

custom:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
    expireHour: 2

spring:
  profiles:
    active: oracle
  datasource:
    url: jdbc:h2:mem:shoppingmall;MODE=Oracle
    username: root
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath*:data-devtest.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: Asia/Seoul
      connection:
        characterEncoding: utf8
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: classpath:/static/
  devtools:
    livereload:
      enabled: true