server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /localh2db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:file:~/kwtworkspace/localDB/localh2db;MODE=MySQL;AUTO_SERVER=TRUE
    username: root
    password: 1234