server:
  port: 8090

spring:
#  h2:
#    console:
#      enabled: true
#      path: /localh2db
  datasource:
    # h2 Setting
    # driver-class-name: org.h2.Driver # com.mysql.jdbc.Driver
    # url: jdbc:h2:file:~/kwtworkspace/localDB/localh2db;MODE=MySQL;AUTO_SERVER=TRUE
    # MySql Setting
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    generate-ddl: true
    # generate-ddl: false
    hibernate:
      ddl-auto: update # develop, not use production JPA 로 개발용으로 사용할때 쓰임, 배포시 schema.sql 로 쿼리 옮겨서 사용
      # ddl-auto: validate ### staging & production, not use production
  batch:
    initialize-schema: always
  jwt:
    secret: kwtjwtsecurekey
    expireHour: 2
security:
  basic:
    enabled: false
#mybatis:
#  type-aliases-package: com.example.myproject.mapper
#  mapper-locations: mybatis/mapper/**/*.xml